<?php

namespace Container1DjnS8N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XDeUaRFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xDeUaRF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xDeUaRF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cleatRepository' => ['privates', 'App\\Repository\\CleatRepository', 'getCleatRepositoryService', true],
        ], [
            'cleatRepository' => 'App\\Repository\\CleatRepository',
        ]);
    }
}
