<?php

namespace Container1DjnS8N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanier2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nCw7CeJ.App\Entity\Panier' shared service.
     *
     * @return \App\Entity\Panier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nCw7CeJ": it references class "App\\Entity\\Panier" but no such service exists.');
    }
}
