<?php

namespace ContainerUxLAWa6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5IyKijD.App\Entity\Cleat' shared service.
     *
     * @return \App\Entity\Cleat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5IyKijD": it references class "App\\Entity\\Cleat" but no such service exists.');
    }
}
