<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQImTxnu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQImTxnu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQImTxnu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQImTxnu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQImTxnu\App_KernelDevDebugContainer([
    'container.build_hash' => 'QImTxnu',
    'container.build_id' => '7f494487',
    'container.build_time' => 1713735378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQImTxnu');
