<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_cleat_index' => [[], ['_controller' => 'App\\Controller\\CleatController::index'], [], [['text', '/cleat/']], [], [], []],
    'app_cleat_new' => [[], ['_controller' => 'App\\Controller\\CleatController::new'], [], [['text', '/cleat/new']], [], [], []],
    'app_cleat_show' => [['id'], ['_controller' => 'App\\Controller\\CleatController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cleat']], [], [], []],
    'app_cleat_edit' => [['id'], ['_controller' => 'App\\Controller\\CleatController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/cleat']], [], [], []],
    'app_cleat_delete' => [['id'], ['_controller' => 'App\\Controller\\CleatController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cleat']], [], [], []],
    'panier_add_cleat' => [['id1', 'id2'], ['_controller' => 'App\\Controller\\CleatController::add_cleat'], [], [['variable', '/', '[^/]++', 'id2', true], ['variable', '/', '[^/]++', 'id1', true], ['text', '/cleat/add-cleat']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginFormController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginFormController::logout'], [], [['text', '/logout']], [], [], []],
    'app_panier_index' => [[], ['_controller' => 'App\\Controller\\PanierController::index'], [], [['text', '/panier/']], [], [], []],
    'app_panier_new' => [[], ['_controller' => 'App\\Controller\\PanierController::new'], [], [['text', '/panier/new']], [], [], []],
    'app_panier_show' => [['id'], ['_controller' => 'App\\Controller\\PanierController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier']], [], [], []],
    'app_panier_edit' => [['id'], ['_controller' => 'App\\Controller\\PanierController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/panier']], [], [], []],
    'app_panier_delete' => [['id'], ['_controller' => 'App\\Controller\\PanierController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier']], [], [], []],
    'panier_delete_cleat' => [['id1', 'id2'], ['_controller' => 'App\\Controller\\PanierController::delete_cleat'], [], [['variable', '/', '[^/]++', 'id2', true], ['variable', '/', '[^/]++', 'id1', true], ['text', '/panier/delete-cleat']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\StaticPages::home'], [], [['text', '/']], [], [], []],
    'compte' => [[], ['_controller' => 'App\\Controller\\StaticPages::login'], [], [['text', '/compte']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
